seed: 0xBADB01
base_name: "facebook/blenderbot-400M-distill"

batch_size: 256
val_batch_size: 256
save_interval: 10_000

dataset:
  max_context_len: 64
  max_target_len: 64

decoder:
  mode: "bert"
  num_hidden_layers: 3
  hidden_size: 512
  intermediate_size: 2048
  num_attention_heads: 8
  hidden_dropout_prob: 0.0
  attention_probs_dropout_prob: 0.0


didi:
  diffusion_steps: 2000
  schedule: "sqrt"
  sampling_mode: "ddpm"
  step_freq: 1
  lr: 1e-3
  warmup_steps: 2_500
  min_lr: 1e-3

trainer:
  devices: 8
  max_steps: 150_000
  val_check_interval: 10_000
