seed: 0xBADB01
#base_name: "facebook/blenderbot-3B"
base_name: "facebook/blenderbot-400M-distill"

batch_size: 64
val_batch_size: 128
save_interval: 10_000

dataset:
  max_context_len: 128
  max_target_len: 128
  multiple_samples_from_threads: False
  single_turn: True

decoder:
  mode: "bert"
  num_hidden_layers: 3
  intermediate_size: 3072
  hidden_dropout_prob: 0.2
  attention_probs_dropout_prob: 0.1

didi:
  diffusion_steps: 2000
  schedule: "sqrt"
  step_freq: 20
  lr: 1e-3
  warmup_steps: 2_500
  min_lr: 5e-5
  s_churn: 80
  s_tmin: 0.05
  s_tmax: 50

trainer:
  devices: 8
  max_steps: 50_000
  val_check_interval: 10_000
  gradient_clip_val: 1.0
  accumulate_grad_batches: 4
