seed: 0xBADB01
base_name: "facebook/blenderbot-3B"
#base_name: "facebook/blenderbot-400M-distill"

batch_size: 64
val_batch_size: 128
save_interval: 10_000

dataset:
  max_context_len: 128
  max_target_len: 128

decoder:
  mode: "bert"
  num_hidden_layers: 12
  intermediate_size: 3072

didi:
  diffusion_steps: 2000
  schedule: "sqrt"
  step_freq: 10
  optimizer: "AdamW"
  lr: 1e-4
  s_churn: 80
  s_tmin: 0.05
  s_tmax: 50

trainer:
  devices: 8
  max_steps: 50_000
  val_check_interval: 10_000
  precision: "bf16-mixed"
