seed: 0xBADB01
base_name: "facebook/blenderbot-400M-distill"
batch_size: 32
save_interval: -1

dataset:
  max_context_len: 128
  max_target_len: 128

decoder:
  mode: "bert"
  num_hidden_layers: 12
  intermediate_size: 3072

didi:
  diffusion_steps: 2000
  schedule: "sqrt"
  step_freq: 10
  optimizer: "AdamW"
  lr: 0.0001
  momentum: 0.95

trainer:
  devices: 1
  accelerator: "gpu"
#  strategy: "ddp"
  max_steps: 1000
  val_check_interval: 1000
