seed: 0xBADB01
#base_name: "facebook/blenderbot-3B"
#base_name: "facebook/blenderbot-400M-distill"
base_name: "bert-base-uncased"

batch_size: 256
val_batch_size: 256
save_interval: 25_000

dataset:
  max_context_len: 64
  max_target_len: 64
  multiple_samples_from_threads: False
  single_turn: True

encoder:
  pretrained: True
  freeze: True

decoder:
  hidden_dropout_prob: 0.2
  attention_probs_dropout_prob: 0.2

didi:
  diffusion_steps: 2000
  schedule: "sqrt"
  sampling_mode: "ddpm"
  step_freq: 1

optimizer:
  lr: 1.5e-4
  scheduler: rsqrt
  warmup_steps: 10_000
  min_lr: None
  weight_decay: 0.0

trainer:
  devices: 8
  max_steps: 200_000
  val_check_interval: 25_000
  gradient_clip_val: 1.0
