seed: 0xBADB01
#base_name: "facebook/blenderbot-400M-distill"
#base_name: "facebook/blenderbot-3B"
#base_name: "google/t5-v1_1-xl"
base_name: "bert-base-uncased"

project_name: "didi"

batch_size: 256
val_batch_size: 256
save_interval: 10_000

dataset:
  max_context_len: 64
  max_target_len: 64

encoder:
  pretrained: True
  freeze: True

decoder:
  hidden_dropout_prob: 0.1
  attention_probs_dropout_prob: 0.1

didi:
  diffusion_steps: 2000
  schedule: "sqrt"
  sampling_mode: "ddpm"
  step_freq: 1
  noise_factor: 1
  anchor_loss: False

optimizer:
  weight_decay: 0.01
  scheduler: linear
  lr: 1e-4
  warmup_steps: 2_500
  min_lr: 0.0
  decay_range: 100_000

trainer:
  devices: 8
  max_steps: 100_000
  val_check_interval: 10_000
  gradient_clip_val: 1.0
